lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/igenomes.config
    - conf/igenomes_ignored.config
nf_core_version: 3.2.1
repository_type: pipeline
template:
  author: Evangelos Karatzas
  description: Generate protein family level models (MSAs, HMMs) starting from a FASTA
    amino acid sequence file.
  force: false
  is_nfcore: true
  name: proteinfamilies
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - fastqc
  version: 1.1.0dev
