lint:
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: Evangelos Karatzas
  description: Generate protein family level models (Multiple Sequence Alignments
    (MSAs), Hidden Markov Models (HMMs)) starting from a FASTA amino acid sequence
    file.
  force: false
  is_nfcore: true
  name: proteinfamilies
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - fastqc
  version: 1.2.0dev
