# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "merge_families"
description: Merge similar protein families by pooling components, merging seed alignments, and generating new family HMM profiles and full alignments
keywords:
  - families
  - merging
  - similarity
  - pooling
  - alignment
  - hmm
  - protein
  - sequences
  - msa
components:
  - pool_similar_components
  - merge_seeds
  - generate_families
  - align_sequences
  - clipkit
  - hmmer/hmmbuild
  - hmmer/hmmsearch
  - filter_recruited
  - hmmer/hmmalign
input:
  - similarities:
      type: file
      description: |
        File containing pairwise similarity data between families
  - seed_msa:
      type: file
      description: |
        Initial seed multiple sequence alignment files that will be merged according to similarities
  - sequences:
      type: file
      description: |
        FASTA file containing input sequences
  - alignment_tool:
      type: string
      description: |
        Tool to use for multiple sequence alignment
      enum: ["famsa", "mafft"]
  - skip_msa_trimming:
      type: boolean
      description: |
        Skip trimming of multiple sequence alignments
  - clipkit_out_format:
      type: string
      description: |
        Output format for ClipKIT trimming tool
      default: "clipkit"
  - hmmsearch_write_target:
      type: boolean
      description: |
        Write target sequences in hmmsearch output
  - hmmsearch_write_domain:
      type: boolean
      description: |
        Write domain information in hmmsearch output
  - skip_additional_sequence_recruiting:
      type: boolean
      description: |
        Skip additional sequence recruiting step
  - hmmsearch_query_length_threshold:
      type: number
      description: |
        Query length threshold for hmmsearch sequence recruitment for full alignments (between 0.0 and 1.0)
      minimum: 0.0
      maximum: 1.0
output:
  - versions:
      type: file
      description: |
        Versions file containing the software versions used in the workflow
  - seed_msa:
      type: file
      description: Generated seed multiple sequence alignment files of merged families
  - full_msa:
      type: file
      description: Full multiple sequence alignment files of merged families
  - fasta:
      type: file
      description: FASTA sequence files of merged families full alignments
  - hmm:
      type: file
      description: Hidden Markov Model profile files of merged families
authors:
  - "@vagkaratzas"
maintainers:
  - "@vagkaratzas"
