# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "CHECK_QUALITY"
description: Subworkflow that checks the quality of input amino acid sequences and exports statistics
keywords:
  - fasta
  - protein
  - statistics
  - quality check
components:
  - seqkit/stats
  - seqkit_stats_to_mqc
input:
  - sequences:
      type: file
      description: |
        Amino acid sequences fasta file.
output:
  - versions:
      type: file
      description: |
        Versions file containing the software versions used in the workflow.
  - seqkit_stats_mqc:
      type: file
      description: |
        Statistics file for MultiQC.
authors:
  - "@vagkaratzas"
maintainers:
  - "@vagkaratzas"
