---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "split_fasta"
description: Split a FASTA file into individual files, one sequence per file
keywords:
  - fasta
  - split
  - sequences
  - protein
tools:
  - "split_fasta":
      description: "Split a FASTA file into individual files, one sequence per file"
      homepage: "https://github.com/nf-core/proteinfamilies/tree/dev/modules/local/split_fasta/"
      documentation: "https://github.com/nf-core/proteinfamilies/tree/dev/modules/local/split_fasta/"
      tool_dev_url: "https://github.com/nf-core/proteinfamilies/tree/dev/modules/local/split_fasta/"
      doi: "10.5281/zenodo.14881993"
      licence: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - fasta:
        type: file
        description: Input FASTA file (.faa)
        pattern: "*.{fa,faa,fasta}"
output:
  split_files:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.faa":
          type: file
          description: Individual FASTA files, one per sequence
          pattern: "*.faa"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
authors:
  - "@vagkaratzas"
maintainers:
  - "@vagkaratzas"
